version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: catalog_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: catalog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
